### ISSUE TITLE
What is status code 3?

### ISSUE THREAD

**Issue by Wouter93** [pogodevorg/pgoapi#91] opened 2016-08-12 12:55 UTC
Suddenly some accounts are getting only status code 3 responses with an empty get_map_data field.

Any idea what this could be?

**Comment by dnsBlah** [comment] 2016-08-12 14:40
You might have provided incorrect data to the proto request.

**Comment by globeriz** [comment] 2016-08-12 17:27
possible duplicate of #80

**Comment by Wouter93** [comment] 2016-08-12 20:24
I don't think it's an ip-ban since other accounts are running just fine. I'm using 10 accounts of which 3 are now constantly returning empty get_map_data  fields and getting status code 3.

Changing the IP has the same effect. Always the same 3 accounts are affected, even when changing their order.

**Comment by dnsBlah** [comment] 2016-08-12 20:36
I have some accounts which only replies on the GET_PLAYER requests.
With status 3 as well
All other requests are dead.

Guess it's permanently banned, however the servers have been down this morning as well...
Maybe it's just a matter of time.

**Comment by NateN1222** [comment] 2016-08-12 20:38
@dnsBlah @Wouter93 It just means that you made a request with bad args

**Comment by Wouter93** [comment] 2016-08-12 22:57
@NateN1222 That's not the problem here, as the posts above have shown
After some manual testing on my phone I found that the 3 accounts are in fact, banned.  Yet somehow the login method succeeds (which probably shouldn't happen)

**Comment by dnsBlah** [comment] 2016-08-13 10:44
because it can login. It can GET_PLAYER
but all other data is unavailable

**Comment by NoOne-dev** [comment] 2016-08-28 03:59
This is a ban - This issue is closed.

**Closed** 2016-08-28 03:59 UTC
